### ISSUE TITLE
Rotate Frequency PGP signing subkey

### ISSUE THREAD

**Issue by demisx** [frequency-chain/frequency#1695]
Similar to https://github.com/LibertyDSNP/frequency/issues/646, renew signing PGP key before it expires. See `FREQUENCY_PGP_SECRET_SUBKEYS` secret in https://github.com/LibertyDSNP/frequency/settings/secrets/actions for the current expiration date. Please note, that only new signing subkey needs to be created. Please note that the master key (primary key) stays as-is.

**Todo:**
-  [ ] Rotate PGP key following instructions in [PGP Wiki](https://github.com/LibertyDSNP/frequency/wiki/PGP)
-  [ ] Create new invitation in the Calendar for @demisx @sbendar with due date at least 2 weeks prior to expiration
- [ ] Ensure this issue stays open, since it's a recurring one.

**Comment by demisx** [comment]
The key has been rotated per instructions in Wiki.
