### ISSUE TITLE
Updates to E2E Tests

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#2003]
We have a grab bag of fixes due to some issues that came to light while trying to run the E2E tests against the Testnet on Paseo.

Going to be a few different PRs, but here's the full list:

- [x] #2010 Split up Staking and Capacity Transaction tests
- [x] #2004 Fix an issue with failing Proxy tests when run against Testnet on Paseo 
- [x] #2004  Switch most tests to use the newer `createSchemaV3`
- [x] #2004 Fix eslint issue with globals
- [ ] #2013 Create a new `getOrCreateSchemaV3` that reuses prior made schemas
- [x] #2004 Fix Not decorating runtime apis without matching versions: CapacityTransactionPaymentRuntimeApi/1
- [x] #2010 Remove the Rococo e2e test workflow (no longer viable)
- [ ] #2013 Move the RPC endpoint for e2e testnet paseo workflow to github vars
- [ ] #2013 Ensure correct endpoint RPC connection
- [ ] #2013 Major speed increases for the capacity transactions test
